spring:
  application:
    name: cashi-challenge

  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: project
    password: project

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 8090

airflow:
  url: 'http://localhost:8080/api/v1'
  user: airflow
  password: airflow
