spring:
  application:
    name: cashi-challenge

  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: project
    password: project

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
